### ISSUE TITLE
Do correlation analysis

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/K3Reviews#1]
Mark and Richel assign different grades to the same K3 songs. How would a scatter plot look like? Would Mark or Richel be the more critical reviewer? Which songs are most differently graded?

**Comment by markwiering** [comment]
So far I have only rated the songs that I like, leaving out the bad ones. It might appear that I like every single song of K3, but that's not the case.

**Comment by richelbilderbeek** [comment]
Sure, I have had the same bias. Now I follow the songs according a playlist its order, resulting in same very bad grades. And I already saw some different gradings, so (for now) I guess I will appear to be the more critical fan.

**Comment by richelbilderbeek** [comment]
Note that this is one of the reasons I use English.

**Comment by richelbilderbeek** [comment]
This Issue has evolved into [https://github.com/richelbilderbeek/k3_article](https://github.com/richelbilderbeek/k3_article), where some real statistics will be done :+1:

Closing this one :rainbow:
